# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerId: ravre03
  imageName: platform-test-app

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'
  
- script: |
    npm run unittests
  displayName: 'Run unit tests'  
      
- script: |
    # Start the app running, and capture the PID so we can kill it later
    node my-simple-app.js &
    APP_PID=$!
    # Install the artillery load testing tool
    npm install -g artillery
    artillery -V
    # Run the artillery load test
    #artillery run -o TEST-artillery.json test/performance/performance.yml
    artillery run tests/performance/performance.yml
    # If test fails, exit 1 to fail this step in the pipeline
    if [ $? -ne 0 ]; then kill $APP_PID && exit 1; fi
    # Generate the Artillery test report
    #artillery report TEST-artillery.json
    #ls -l
    # Display Artillery test results in log
    #cat TEST-artillery.json
    
    # Kill the app
    kill $APP_PID
   displayName: 'Run Artillery performance test'    
    
- script: |
    docker build -t $(dockerId)/$(imageName) .     
  displayName: 'Build the Docker Image' 
  
